### PR TITLE
Change to version declaration to PyQt5>=5.15

### PR DESCRIPTION
**Pull request by gudlot**

### CODE REVIEW

**Comment by malte-storm** [comment]
Your suggested fix does not work for other platforms. The [pyqt5-qt5](https://pypi.org/search/?q=pyqt5-qt5) package in version 5.15.14 is only supported for macOS, not for Windows or Linux.

**Comment by gudlot** [comment]
5.15.14 is the version automatically selected after running `pip-compile pyproject.toml` on MacOS. I removed the specific version for pyqt5-qt5 in requirements.txt before, so `pip-compile pyproject.toml` was able to run through.

**Comment by gudlot** [comment]
I created a fresh python 3.12.4 env on a Mac with . The current installation recipe did not work on a Mac M2:
```
INFO: pip is looking at multiple versions of pydidas to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement pyqt5-qt5==5.15.2 (from pydidas) (from versions: 5.15.11, 5.15.12, 5.15.13, 5.15.14)
ERROR: No matching distribution found for pyqt5-qt5==5.15.2
```

I solved this as follows

```
installed pip-tools
```

Removed in `pyproject.toml` the version number for `PyQt5`
```diff
diff --git a/requirements.in b/requirements.in
index a73342e2..99c10817 100644
--- a/requirements.in
+++ b/requirements.in
@@ -13,6 +13,6 @@ qtpy>=2.4.0
 hdf5plugin>=4.4.0
 pyyaml>=6.0
 requests>=2.31.0
-PyQt5==5.15.10
+PyQt5
 build>=1.0.3
 setuptools>69.0.0
\ No newline at end of file
```

Installed `pip-tools` into my environment and executed `pip-compile requirements.in`
Result: new requirements.txt
```diff
diff --git a/requirements.txt b/requirements.txt
index 7b86fd42..5b16ab4c 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,8 +1,8 @@
 #
-# This file is autogenerated by pip-compile with Python 3.11
+# This file is autogenerated by pip-compile with Python 3.12
 # by the following command:
 #
-#    pip-compile
+#    pip-compile requirements.in
 #
 accessible-pygments==0.0.5
     # via pydata-sphinx-theme
@@ -20,10 +20,6 @@ certifi==2024.6.2
     # via requests
 charset-normalizer==3.3.2
     # via requests
-colorama==0.4.6
-    # via
-    #   build
-    #   sphinx
 contourpy==1.2.1
     # via matplotlib
 cycler==0.12.1
@@ -121,7 +117,7 @@ pyproject-hooks==1.1.0
     # via build
 pyqt5==5.15.10
     # via -r requirements.in
-pyqt5-qt5==5.15.2
+pyqt5-qt5==5.15.14
     # via pyqt5
 pyqt5-sip==12.13.0
     # via pyqt5
```

Finally, `python -m pip install .` into a freshly cloned repo.  A `pydidas-gui` started the gui.

**Comment by malte-storm** [comment]
As you can check on the pypi.org website, ``pyqt5-qt5==5.15.14`` does not have a valid windows distribution. 
The default should be compatible with both linux and windows platforms.
I am not against changing the requirements for mac but then please make the changes mac-specific with the respective ``platform_system`` as check.

**Comment by malte-storm** [comment]
Has become redundant with #65

**Pull request closed without merging**
